### ISSUE TITLE
Upgrade manifest version and publish to chrome store

### ISSUE THREAD

**Issue by GabrielDelepine** [mshauneu/chrome-swagger-ui#8]
Thanks for maintaining this repository !

Could you iterate the manifest version and upgrade the package to the chrome store ?

Thanks !

![screenshot from 2016-12-21 12-08-26](https://cloud.githubusercontent.com/assets/1979087/21387412/d609213c-c777-11e6-9c66-1a81a08b10da.png)

**Comment by mshauneu** [comment]
New version was published.
